print("Choice Of Operations")
print("1.ADD")
print("2.Subtract")
print("3.Multiplication")
print("4.Division")
choice<-as.integer(readline(prompt="Enter your choice"))
num1<-as.double(readline(prompt = "Enter your first number"))
num2<-as.double(readline(prompt = "Enter your second number"))
result<-switch(choice,(num1+num2),(num1-num2),(num1*num2),(num1/num2))
print(paste("the result is:",result))
